# use node:<version>-slim as basic image for node environment
FROM node:17-slim
MAINTAINER Shutong Chen
# working directory is /usr/src/app
WORKDIR /usr/src/app
# copy package.json into the container first and then install dependencies
COPY ./package*.json ./
RUN npm install
# copy the source files under local directory into container
COPY . .
# port 8000 will be used for listening server side
EXPOSE 8000
# start server once the container has been created
CMD ["index.js" ]