#choose an OS image
FROM ubuntu
MAINTAINER Shutong Chen
ENV DEBIAN_FRONTEND=noninteractive
#install required software and dependencies of webserver
RUN apt-get update
RUN apt-get install apache2 -y
RUN apt-get install apache2-utils -y
RUN apt-get clean
#copy customized index.html from local machine
COPY index.html /var/www/html
#set ServerName localhost to specify the rendering address
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN service apache2 restart
#expose port 80 if you are serving content over http and run the webserver
EXPOSE 80
CMD ["apache2ctl","-D","FOREGROUND"]